In [51]:
import pandas as pd

In [52]:
input_txt_file = 'dataset.txt'

In [53]:
output_csv_file = 'dataset.csv'

In [54]:
df = pd.read_csv(input_txt_file, sep=',')

In [55]:
df.head()

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
2,3,Robert Johnson,NaN,Hat,2015-03-20,12.99,4.2,Newspapers
3,4,Sarah Williams,35.0,Jeans,2015-04-05,39.99,4.0,NaN
4,5,Michael Brown,32.0,Shirt,2015-05-12,NaN,3.5,Social Media

In [56]:
df.to_csv(output_csv_file, index=False)

In [57]:
print(f"Data from '{input_txt_file}' saved to '{output_csv_file}' successfully.")

Data from 'dataset.txt' saved to 'dataset.csv' successfully.

In [58]:
df = pd.read_csv(input_txt_file, sep=',')

In [59]:
df

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
2,3,Robert Johnson,NaN,Hat,2015-03-20,12.99,4.2,Newspapers
3,4,Sarah Williams,35.0,Jeans,2015-04-05,39.99,4.0,NaN
4,5,Michael Brown,32.0,Shirt,2015-05-12,NaN,3.5,Social Media
...,...,...,...,...,...,...,...,...
95,96,Isabella Lee,35.0,Shirt,2014-10-02,18.99,4.4,Newspapers
96,97,Noah Turner,27.0,Shoes,NaN,99.99,4.9,Social Media
97,98,Mia Miller,38.0,Jeans,2014-11-16,44.99,4.2,TV
98,99,Charlotte Wilson,36.0,Shirt,2014-12-23,26.99,NaN,Newspapers
99,100,Mason Davis,27.0,Shoes,2013-01-30,79.99,4.8,Social Media

In [60]:
df.drop_duplicates()

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
2,3,Robert Johnson,NaN,Hat,2015-03-20,12.99,4.2,Newspapers
3,4,Sarah Williams,35.0,Jeans,2015-04-05,39.99,4.0,NaN
4,5,Michael Brown,32.0,Shirt,2015-05-12,NaN,3.5,Social Media
...,...,...,...,...,...,...,...,...
95,96,Isabella Lee,35.0,Shirt,2014-10-02,18.99,4.4,Newspapers
96,97,Noah Turner,27.0,Shoes,NaN,99.99,4.9,Social Media
97,98,Mia Miller,38.0,Jeans,2014-11-16,44.99,4.2,TV
98,99,Charlotte Wilson,36.0,Shirt,2014-12-23,26.99,NaN,Newspapers
99,100,Mason Davis,27.0,Shoes,2013-01-30,79.99,4.8,Social Media

In [61]:
df

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
2,3,Robert Johnson,NaN,Hat,2015-03-20,12.99,4.2,Newspapers
3,4,Sarah Williams,35.0,Jeans,2015-04-05,39.99,4.0,NaN
4,5,Michael Brown,32.0,Shirt,2015-05-12,NaN,3.5,Social Media
...,...,...,...,...,...,...,...,...
95,96,Isabella Lee,35.0,Shirt,2014-10-02,18.99,4.4,Newspapers
96,97,Noah Turner,27.0,Shoes,NaN,99.99,4.9,Social Media
97,98,Mia Miller,38.0,Jeans,2014-11-16,44.99,4.2,TV
98,99,Charlotte Wilson,36.0,Shirt,2014-12-23,26.99,NaN,Newspapers
99,100,Mason Davis,27.0,Shoes,2013-01-30,79.99,4.8,Social Media

In [62]:
df = df.dropna()

In [63]:
df

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
5,6,Lisa Davis,45.0,Shoes,2015-06-18,89.99,4.8,TV
9,10,Amy Thompson,29.0,Jeans,2015-10-21,37.99,3.9,TV
10,11,Adam Clark,33.0,Shirt,2015-11-28,22.99,4.3,Newspapers
...,...,...,...,...,...,...,...,...
93,94,Olivia Brown,31.0,Shoes,2014-07-18,89.99,4.9,Social Media
94,95,Liam Anderson,33.0,Jeans,2014-08-25,49.99,4.0,TV
95,96,Isabella Lee,35.0,Shirt,2014-10-02,18.99,4.4,Newspapers
97,98,Mia Miller,38.0,Jeans,2014-11-16,44.99,4.2,TV
99,100,Mason Davis,27.0,Shoes,2013-01-30,79.99,4.8,Social Media

In [64]:
df=df.reset_index(drop=True)
df

,custID,custName,Age,Product,DatePurchased,Price,RatingOfProduct,AdvertisingAgency
0,1,John Doe,30.0,Shirt,2015-01-10,25.99,4.5,Social Media
1,2,Jane Smith,28.0,Shoes,2015-02-15,59.99,3.8,TV
2,6,Lisa Davis,45.0,Shoes,2015-06-18,89.99,4.8,TV
3,10,Amy Thompson,29.0,Jeans,2015-10-21,37.99,3.9,TV
4,11,Adam Clark,33.0,Shirt,2015-11-28,22.99,4.3,Newspapers
...,...,...,...,...,...,...,...,...
63,94,Olivia Brown,31.0,Shoes,2014-07-18,89.99,4.9,Social Media
64,95,Liam Anderson,33.0,Jeans,2014-08-25,49.99,4.0,TV
65,96,Isabella Lee,35.0,Shirt,2014-10-02,18.99,4.4,Newspapers
66,98,Mia Miller,38.0,Jeans,2014-11-16,44.99,4.2,TV
67,100,Mason Davis,27.0,Shoes,2013-01-30,79.99,4.8,Social Media

In [67]:
df.to_csv(output_csv_file, index=False)

In [68]:
print(f"Data from '{input_txt_file}' saved to '{output_csv_file}' successfully.")

Data from 'dataset.txt' saved to 'dataset.csv' successfully.